FROM frolvlad/alpine-glibc

RUN apk update && \
    apk add --no-cache \
      sudo file zsh tmux git vim wget curl htop rsync \
      strace ltrace tree make cmake elfutils binutils \
      gdb python3-dev cargo \
      g++ mingw-w64-gcc nasm radare2 \
      libc-dev linux-headers libffi-dev \
      bc bison flex perl openssl-dev ruby-dev

RUN if [ ! -e /usr/bin/python ]; then ln -sf python3 /usr/bin/python ; fi && \
    python3 -m ensurepip && \
    python3 -m pip install --no-cache-dir -U pip setuptools wheel && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
    python3 -m pip install --no-cache-dir pwntools unicorn capstone ropper keystone-engine

RUN gem install --no-document one_gadget seccomp-tools

ENV PATH="/root/bin:${PATH}"
ENV LANG="en_US.UTF-8"

COPY root /root

CMD ["/usr/bin/zsh"]
