FROM ubuntu:20.10

RUN apt-get update -qq

RUN apt-get install -y -qqq --no-install-recommends \
    sudo file zsh tmux git vim wget curl htop rsync \
    strace ltrace tree make cmake elfutils \
    gdb locales python3 python3-pip binutils \
    gcc musl-tools nasm radare2 \
    build-essential libncurses-dev libssl-dev libffi-dev \
    bc bison flex perl openssl ruby && \
    apt-get purge -y && \
    apt-get clean -y

RUN locale-gen --purge "en_US.UTF-8" && \
    echo -e 'LANG="en_US.UTF-8"\nLANGUAGE="en_US:en"\n' >> /etc/default/locale && \
    dpkg-reconfigure --frontend=noninteractive locales

RUN if [ ! -e /usr/bin/python ]; then ln -sf python3 /usr/bin/python ; fi && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
    python3 -m pip --no-cache-dir install pwntools unicorn capstone ropper keystone-engine

RUN gem install --no-document one_gadget

COPY root /root

CMD zsh
