#!/usr/bin/env bash

docker ps > /dev/null || exit 255

version=$(basename "$0")
version=${version#vm}
version=${version#-}
if [ ! "$version" ]; then
  version='latest'
fi

name="vm_${version}_$(pwd | sha1sum | awk '{print $1}')"

argv=()
while [[ $# -gt 0 ]]; do
  if [[ $1 == -* ]]; then
    argv+=("$1 $2")
    shift
    shift
  else
    break
  fi
done
args="${argv[*]}"

cmd="zsh"
if [ $# -gt 0 ]; then
  cmd="$*"
fi

>&2 echo "name: $name"
>&2 echo "args: $args"
>&2 echo "cmd: $cmd"

exist=$(docker ps -q -f "name=$name")
already_run=$(pgrep -lf 'docker run' | grep -c "$name")
if [[ ! $exist ]] && [[ $already_run -eq 0 ]]; then
  >&2 echo -n 'start container: '
  docker run --rm -dt \
    --name "$name" \
    -v "$PWD:/data" \
    --cap-add=SYS_PTRACE \
    --security-opt seccomp=unconfined \
    $args \
    nella17/vm:$version
fi

docker exec -it -w '/data' "$name" zsh -c "source ~/.zshrc && $cmd"

count=$(pgrep -lf 'docker exec' | grep -c "$name")
exist=$(docker ps -q -f "name=$name")
if [[ $count -eq 0 ]] && [[ $exist ]]; then
  >&2 echo -n 'shutdown container: '
  docker stop "$name"
fi
