# scrollback buffer n lines
set -g history-limit 10000
# split windows (create pane)
bind-key _ split-window -v -c '#{pane_current_path}'
bind-key | split-window -h -c '#{pane_current_path}'
# vi-style controls for copy mode
setw -g mode-keys vi

bind-key r command-prompt -p 'Command >> ' "split-window -c '#{pane_current_path}' -h '%%; echo \"Press enter to continue.\"; read;'"

setenv LANG 'en_US.UTF-8'
