name: Generate Dockerfiles

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    name: Generate Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python generate.py
      - run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -f Dockerfiles/*
          git commit -m "build dockerfiles"
          git push https://${GITHUB_ACTOR}:${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git HEAD:deploy
