name: Generate Dockerfiles

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  IMAGE_NAME: ${{ github.repository }}

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  builder:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
        - 'devel'
        - 'rolling'
        - 'latest'
        - '22.04'
        - '20.04'
        - '18.04'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: sed -i 's/tag/${{ matrix.tag }}/' Docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.LOGIN_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

